version: '3.8'

networks:
  infrastructure:

services:
  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
