version: '3.8'

networks:
  infrastructure:

services:
  mosquitto: 
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
    networks:
      - infrastructure
    restart: always
    volumes:
      - mosquitto_data:/mosquitto

  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    container_name: portainer
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.rule=Host(`portainer.home`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - infrastructure
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  traefik:
    image: traefik:v2.7
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.rule=Host(`traefik.home`)
      - traefik.http.routers.dashboard.service=api@internal
    networks:
      - infrastructure
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
    
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.zigbee2mqtt.entrypoints=web
      - traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.home`)
      - traefik.http.services.zigbee2mqtt.loadbalancer.server.port=80
    networks:
      - infrastructure
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro

volumes:
  mosquitto_data:
  portainer_data:
